[server]
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 5

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#1D3E72"
backgroundColor = "#F8F6EE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14213F"
font = "sans serif"
